
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "E:/cmake-3.29.0-rc3-windows-x86_64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "E:/cmake-3.29.0-rc3-windows-x86_64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
...
